import os
from openai import OpenAI
from dotenv import load_dotenv

# .env 파일에서 환경 변수 로드
load_dotenv()

# OpenAI 클라이언트 초기화
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# 파인튜닝된 모델 ID (여기에 실제 ID를 넣으세요)
FINE_TUNED_MODEL = "ft:gpt-3.5-turbo-0125:personal::ACMv2sYu"

def get_feedback(text):
    response = client.chat.completions.create(
        model=FINE_TUNED_MODEL,
        messages=[
            {"role": "system", "content": "당신은 논문 작성을 지도하는 경험 많은 교수입니다. 주어진 텍스트를 검토하고 구체적이고 건설적인 피드백을 제공해주세요."},
            {"role": "user", "content": f"다음 텍스트를 검토하고 개선사항을 제안해주세요: {text}"}
        ],
        max_tokens=1000
    )
    return response.choices[0].message.content

# 테스트
test_text = """
Yunhyae Kim - Research Statement  (As of September 20, 2022)

My dissertation project “The Production of Democracy” develops a theory of hierarchy and democracy in which the political order is co-constituted by the organization of production and the organization of electoral-legislative politics. By ‘organization of production,’ I mean the ways social institutions structure productive cooperation by assigning rights and obligations such as ownership of productive assets, eminent domain, control rights over managerial decisions, obligations to work, and the right to strike. The following offers an introduction to the three parts of the dissertation project. Our economic cooperation is characterized not only by distributive inequalities but also by asymmetrical relations of power and authority (Part I) and that the democratic state is structurally constrained by the organization of production in its power, legitimacy, and knowledge (Part II). I therefore argue that we should reject the widely accepted view that construes the economy as a merely distributive, sub-political domain below the state. It should be replaced with a dual-core view of democratic politics where democratic production and democratic state politics stand in a relationship of mutual dependence (Part III).

Part I. The Hierarchical Economy
The first part aims at developing an adequate theory of contemporary advanced industrialized economies that offers (i) their normatively and descriptively (i.e., social theoretically) accurate representation, which (ii) is grounded in their institutional landscape distinct from classical capitalism, and (iii) demonstrates not merely their distributively unequal but relationally unequal—in short, hierarchical—character (iv) without relying on metaphysically heavy group-agent concepts or highly abstract metaphors (capitalized ‘Capital’ or ‘Labor’). My dissertation currently has two chapters that respectively focus on labor and capital.

1. The Subjection of Workers
Are workers problematically subject to the authority of their employers? If so, what does the subjection consist in? Libertarians argue that the firm is a network of voluntary contracts with no place for subordination. Elizabeth Anderson (2017) and many liberal egalitarians rightly disagree but for wrong reasons. They believe workers’ subjection consists in the intra-firm fact that workers are monitored, directed, and sanctioned by managers. This account fails to refute the libertarian vision since contemporary workers, unlike their 19th-century counterparts, seem to have a standing freedom to exit employment in virtue of (i) the welfare state and (ii) the non-enforcement of ‘specific performance’ by the legal regime. That is, even when workers breach their employment contracts, they would not be forced to return to the job and perform the work. I instead propose a two-tier account, according to which workers’ subjection consists in the joint truth of (1) the intra-firm managerial authority and (2) the society-wide economic structure that leaves them no reasonable alternative to employment. A proper account of workers’ subjection must refer to wide-ranging institutional facts about workfare regimes, market distribution of consumer goods, private control of productive resources, the option of self-employment, the imperative of large-scale production, access to credit, and obstacles to setting up and running worker cooperatives.

2. Ownership and Hierarchy
Should capital ownership be of concern to those committed to the ideal of democratic equality, which condemns asymmetrical relations of power and authority? The silence of most contemporary political theorists and philosophers seems to say ‘no.’ The widespread concern about workplace hierarchy either explicitly targets managers or ‘bosses’ or in targeting ‘the capitalists,’ relies on anachronistic ambiguation between managers and capital owners. Against the background of the philosophical vacuum, this paper makes a twofold contribution. First, I construct an explicit defense of the dominant view by situating the silence in the context of the evolved institutions of contemporary financialized corporate capitalism, where each joint-stock company has a diverse pool of non-majority shareholders, who are often institutional investors such as pension funds and asset management companies, and when the control over the corporation and workers is vested in managers. Second, I argue that private capital ownership is nonetheless an essential aspect of the hierarchical economy. At the macro level, it continues to serve as a unified locus of two primary incidents of property rights: (1) the right to financially benefit from economic cooperation in a concentrated accumulative form and (2) the right to control investment and thereby control the goals and terms of economic cooperation. Capital ownership is a political office in the governing regime of productive cooperation.

Part II. The Democratic State: The “Mortal God” to the Rescue? 
Yet economic hierarchy is often regarded as not deeply problematic in the way political hierarchy is. While it is taken for granted that state political institutions are to live up to the demanding, non-overridable requirement of democracy to secure equality in power and right to influence political decisions, such requirement is thought to be easily overridden or absent altogether in economic institutions. Many theorists of workplace hierarchy often argue for merely taming managerial power by weaker forms of worker participation that stop short of full democracy. Principled discussion of democratization of the entire economy including investment and public sector employment is still shockingly scarce compared to the entire history of political thought devoted to democratization of state political power.
In the background of the normative double standard lies the idea of the state sovereign over the economy. However powerful capital owners and managers are, they are subject to the authority and power of the democratic state. Whatever is problematic about the hierarchical economy can be addressed by the state’s repertoire of political solutions such as taxation, redistribution, and regulation. And democratic elections and legislation secure the economically powerless an egalitarian sphere of political participation. The philosophical expression of this idea has been that the democratic political institutions make the economic hierarchy unobjectionable by ‘controlling and regulating’ the economy ‘from a higher-level standpoint of equality.’ Call this the State-Above-the-Economy Argument against democratic justice in production.
Chapters 3 to 5 of my dissertation critically examine and reject this argument. The Argument presupposes that the democratic state, just like ‘the mortal God,’ is all-powerful, all-good (legitimate), and all-knowing vis-à-vis the economy. I argue that it is instead structurally constrained by the economy in its power, legitimacy, and knowledge.

3.	The State as the Commander of the Economy.
This chapter critiques the vision of the omnipotent state by showing how private organization of production involves partial alienation of political power. The private economy either directly delimits or structurally constrains the power the state may exercise over different objects of control (e.g., identity of the incumbents of economic positions, economic goals or policies, or the economic structure) and manners of control (e.g., direct authority/command, inducements, sanctions). Importantly, while Thomas Christiano (2010) proposes to solve this problem by subordinating the private economy to the democratic assembly, I argue that this solution fails because the private economy not only constrains the implementation but also the formation of the democratic will. A version of my argument in this chapter is available as a stand-alone paper entitled “Is the structural dependence of the state on capital a problem of capitalist insubordination?”

4.	The State as the Authorizer of the Economy. 
This chapter argues an adequate economic constitution, not just a political constitution, is prior to state legitimacy. This claim is developed as a response to the following defense of the State-Above-the-Economy Argument. The limits on state power posed by private economy are unproblematic insofar as they are democratically authorized. Democratic self-rule, the thought goes, involves reconciling oneself to the limits collectively decided upon and making choices therewithin even when those limits seem problematic. This view presupposes political goodness or legitimacy of the democratic political procedures of the state irrespective of the hierarchy of the economy—as if divine omnibenevolence is assumed irrespective of the evils of the world. I argue that this presupposition must be rejected. Because the democratic will is formed under the constraints of the economy, the state political institutions cannot claim legitimacy independently of the economic structure.

5.	The State as the All-Knower of the Economy. 
The idea that the state controls and makes legitimate political decisions about the economy implicitly assumes that the state is omniscient, i.e., has unconstrained access to information about the economy. This chapter develops a critique of this conception of the state as omniscient institution on the basis of (1) the general limits on state knowledge present in any feasible and justifiable politico-economic system, and (2) the constraints on the state knowledge posed by specifically private economy in the form of intellectual property, proprietary information, trade secrets, or patents. I show how the epistemic dependence of the state on the economy has been a common concern across ideological spectrum as in Hayek, Marx, and James Scott). I also draw upon concrete historical cases. For example, epistemic concerns about the opacity of production costs motivated nationalization attempts during the American wartime industrial mobilization; and the trade secret protections for the semiconductor producers in South Korea constrained the court decision making over workers’ occupational diseases developed in semiconductor factories.

Part III. Reframing and Reimagining: The Democratic Politico-Economic Interdependence
The third part of the project reframes existing questions and (re)opens neglected questions in light of the first two parts. That is, when our economic cooperation is hierarchically organized and when the democratic state falls short of neutralizing but is instead structurally constrained by the economic hierarchy, what does democratic justice require of our economic institutions? My research questions are currently structured around the following themes.

What, if anything, is undemocratic about structural dependence? 
Much of existing treatment of the structural dependence of the state on capital regards it as undemocratic. The charge of democratic defect presupposes a democratic state-economy relationship. However, we do not yet have an adequate theory of this topic. I argue so by examining and rejecting two candidate theories. According to the Subordination View, all patterns of structural dependence are problematic because they constitute failures of the state political institutions to maintain independence from and subordinate the economy. This is implausible. The democratic state cannot and should not seek to subordinate the economy because it requires totalitarian elimination of local discretion of producers, when producer discretion deserves protection as they implicate important interests of democratic citizenship. Nor is the opposite view defensible, according to which no structural dependence is problematic. Democratic self-determination, especially transformation, of the economy is impossible when the state is excessively constrained by the economic powers to the extent that it is inefficacious. What we need is a theory of the democratic form of state-economy interdependence. 

Workplace Democracy: Reframing the Debate.
The state-economy interdependence informs what a full-fledged defense of workplace democracy should look like and demands reconsideration of prominent existing arguments. On the one hand, it removes the strongest objection to workplace democracy. Contrary to the State-Above-the-Economy Argument, the opportunity for political participation qua citizen does not compensate for the disempowerment in the economy qua worker. On the other hand, the interdependence gives rise to a different pro tanto objection to workplace democracy. The democratic state often offers the only institutional avenue of political influence for the marginalized and vulnerable such as the disabled, the elderly, and those who perform informal ‘care labor’ for them. When their interests or preferences conflict with those of immediate producers in the formal economy, robust protection of producer self-management could diminish political power of the marginalized. 
This challenge calls for a sophisticated defense of workplace democracy that clarifies the following institutional backgrounds and requirements. (1) Is the state at issue well-positioned to protect the interests of the vulnerable? Or is it constrained to protect interests of the established economic powers? (2) What is the legitimate domain of state politics versus of producer self-management? What kinds of productive obligations can the state legitimately impose on immediate producers? (3) Are there particularly urgent interests of producers that deserve protection from the demands from the democratic state?

The Right to Strike: Civil Disobedience at Work
According to the mainstream conception, the right to strike is an economic right that compensates for workers’ weaker bargaining power for the sake of distributive fairness. In contrast, the existing political conception (Gourevitch 2018) is grounded in non-ideal justification and construes it as a right to resist the oppression inherent in capitalism. This work explores an alternative political conception that does not presuppose the fundamental injustice of the system. The basic thought is that the right to strike can be understood as a form of the right to civil disobedience at work. That is, it is the right to disobey a productive decision that workers are subject to and yet regard as unjustifiable. Unlike the economic conception, the right to strike is understood as a political right that merits constitutional protection. Unlike the non-ideal radical conception, first, it defends protection of the right to strike against the background of disagreements as to the fundamental injustice of the system. Second, it reimagines the place of the right to strike in the ideal democratic order, which I take to be prefigured by the workers’ self-understanding in recent strikes and protests I draw upon.

The Dilemma of the State-Constituting Labor. 
Should public sector workers be granted participatory labor rights such as the right to strike or the right to workplace democracy? I argue that this question involves a dilemma, which has gone unrecognized by the almost exclusive assumption of private sector employment in the literature. On the one hand, we have a prima facie case for granting the same rights to public workers. They labor in subjection to authority, who can exercise arbitrary power or make decisions that radically fail to align with their judgment. The conventional prohibition on public sector strikes based on their ‘essential labor’ is also dubious insofar as we believe private sector essential workers are rightly granted the constitutional right to strike. However, securing labor rights for public workers could undermine or even deconstruct democratic state power. What if the police union democratically decided that they will only marginally accommodate the popular demand for its reform? What if bureaucrats, to protect immigrants from the xenophobic president, together adopted an interpretation of the federal guidance that effectively nullifies its intended force? I plan to explore democratic principles that could guide our political thinking as I bring out the normative implications of the neglected fact that state power consists in a type of ‘productive power,’ i.e., power over others’ organized performance of labor.

Social Reproduction, Transformation, and Feminist Philosophy as Normative Social Theory
Part of my research agenda involves putting feminist philosophy into conversation with socialist philosophy. Their intersecting place offers generative resources for tackling their distinct yet similar problems in theory and practice. For example, when there do not seem to be common interests, experiences, or social properties shared by all women or all workers, who or what is the subject of feminist or socialist theory? Is gender or class appropriately understood as groups? What is the role of identity in understanding and transforming unjust social structures? When the fundamental interests of the most vulnerable depend on the submission of the oppressed to injustice—as in the dependence of the disabled upon underpaid care labor by immigrant women—what does justifiable and effective exercise of organized power look like? Although my thinking in this area is at an earlier stage than my dissertation project, the following working paper lays the groundwork.

Does the Extension of Woman Matter? Gender Identity and Social Reproduction
Which question should guide feminist theorizing? The dominant answer in (analytic) feminist philosophy has been “Who are women? What does ‘woman’ mean?” interpreted as the extension question, namely, “What is the necessary and sufficient condition of womanhood?” This paper argues that feminist theorizing should instead be guided by the reproduction question (“How are unjust gender structures persistently reproduced?” partnered with the transition question (“What are the justifiable and effective pathways to transformation of the unjust structures?”). The argument is two-fold. I debunk and explain away the apparent fundamentality of the extension question. I draw upon parallels in socialist practice and theory: the on-the-ground politics regarding the workerhood of platform workers and the theoretical debates on the workerhood of ‘the new middle class.’ On the other hand, I show that a reproduction-oriented theory can offer doubly grounded justification for trans gender identity claims and thereby accommodate the main motivation for the extension-oriented theory.

"""

feedback = get_feedback(test_text)
print("피드백:")
print(feedback)